name: Deploy to web.shuttletracker.app (3)

on:
  workflow_dispatch:

jobs:
  web-shuttletracker-app:
    name: Deploy to staging (3)
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      environment: staging
    secrets:
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING_3 }}
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
