name: Deploy to staging-api-shuttles.rpi.edu (2)

on:
  workflow_dispatch:

jobs:
  staging-api-shuttles:
    name: Deploy to staging (2)
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      environment: staging
    secrets:
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING_2 }}
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
